apiVersion: v1
kind: Secret
metadata:
  name: repository-pat
  namespace: wac-hospital

type: Opaque
stringData:
  username: "xkello" # zvyčajne môže byť akékoľvek meno
  password: "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"  # vygenerovaný PAT