apiVersion: v1
kind: Secret
metadata:
  name: repository-pat
  namespace: wac-hospital

type: Opaque
stringData:
  username: xkello # zvyčajne môže byť akékoľvek meno
  password: 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  # vygenerovaný PAT