apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xkello/ambulance-ufe
    newName: xkello/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20250225.1252 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
