apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xkello-ambulance-ufe-content
spec:
  microFrontend: xkello-ambulance-ufe
  element: xkello-ambulance-wl-app
  attributes:
    - name: api-base
    - value: http://localhost:5000/api
    - name: ambulance-id
    - value: bobulova
    - name: base-path
      value: /xkello-ambulance-wl/
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?xkello-ambulance-wl(/.*)?$"