apiVersion: apps/v1
kind: Deployment
metadata:
  name: xkello-ambulance-webapi

spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /xkello-openapi
            - name: BASE_URL
              value: /xkello-openapi-ui